# level of progress messages written to the console. One of: "off", "severe", "warning", "info", "config", "fine",
# "finer", "finest". "debug" (an alias for "fine") "trace" (an alias for "finer"), and "all" (an alias for "finest")
# are also accepted.
logLevel: CONFIG
